version: '3'
services:
  ts-cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    networks:
      - task-scheduler-network
networks:
  task-scheduler-network:
    external: true

#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
