version: '3'
services:
  task-scheduler-consumer:
    image: com.dotterbear/task-scheduler-consumer
    networks:
      - default
      - task-scheduler-network
networks:
  task-scheduler-network:
    external: true
