spring.kafka:
  bootstrap-servers: kafka:9092
  template.default-topic: task-scheudler
  listener.concurrency: 3

spring.data.cassandra:
  contact-points: 172.22.0.2
  port: 9042
  keyspace-name: local_test
  schema-action: CREATE_IF_NOT_EXISTS

logging.level:
  org.springframework.web: DEBUG
  com.dotterbear: DEBUG

com.dotterbear:
  task.consumer.thread: 5
  nodes.scheduler.assume.alive: 120